[package]
name = "id-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "idmanager"
path = "src/lib.rs"

[[bin]]
name = "usage"
path = "src/examples/usage.rs"

[dependencies]
num="*"
